
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  DatasetCycle: 'DatasetCycle'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable',
  Snapshot: 'Snapshot'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const DatasetCycleScalarFieldEnum = {
  LoadID: 'LoadID',
  ShiftId: 'ShiftId',
  ShiftDate: 'ShiftDate',
  Bin5Mins: 'Bin5Mins',
  Bin15Mins: 'Bin15Mins',
  Bin30Mins: 'Bin30Mins',
  Bin60Mins: 'Bin60Mins',
  LoadPit: 'LoadPit',
  LoadRegion: 'LoadRegion',
  LoadLocation: 'LoadLocation',
  DumpLocation: 'DumpLocation',
  ExcavID: 'ExcavID',
  ExcavSize: 'ExcavSize',
  ExcavType: 'ExcavType',
  ExcavOperatorID: 'ExcavOperatorID',
  ExcavDeptID: 'ExcavDeptID',
  ExcavOwnerID: 'ExcavOwnerID',
  TruckID: 'TruckID',
  TruckSize: 'TruckSize',
  TruckType: 'TruckType',
  TruckOperatorID: 'TruckOperatorID',
  TruckDeptID: 'TruckDeptID',
  TruckOwnerID: 'TruckOwnerID',
  AssignToFrontTimestamp: 'AssignToFrontTimestamp',
  ExpctdEmptyTravelSec: 'ExpctdEmptyTravelSec',
  EmptyTravDurationSec: 'EmptyTravDurationSec',
  HangTimeSec: 'HangTimeSec',
  ArriveAtFrontTimestamp: 'ArriveAtFrontTimestamp',
  QueTimeSec: 'QueTimeSec',
  SpottingTimestamp: 'SpottingTimestamp',
  SpotTimeSec: 'SpotTimeSec',
  LoadingTimestamp: 'LoadingTimestamp',
  LoadingTimeSec: 'LoadingTimeSec',
  FullTimestamp: 'FullTimestamp',
  ExpctdFullTravelSec: 'ExpctdFullTravelSec',
  FullTravDurationSec: 'FullTravDurationSec',
  ArriveAtDumpTimestamp: 'ArriveAtDumpTimestamp',
  DumpTimeSec: 'DumpTimeSec',
  EmptyTimestamp: 'EmptyTimestamp',
  TrucksInQueTimeFull: 'TrucksInQueTimeFull',
  MaterialID: 'MaterialID',
  EmptyDistKM: 'EmptyDistKM',
  FullDistKM: 'FullDistKM',
  FieldFirstDipper: 'FieldFirstDipper',
  FieldLastDipper: 'FieldLastDipper',
  TonsAtLoad: 'TonsAtLoad',
  TonsAtDump: 'TonsAtDump',
  TruckFactor: 'TruckFactor',
  Elocked: 'Elocked',
  DiffPass1: 'DiffPass1',
  DiffPass2: 'DiffPass2',
  DiffPass3: 'DiffPass3',
  DiffPass4: 'DiffPass4',
  DiffPass5: 'DiffPass5',
  DiffPass6: 'DiffPass6',
  DiffPass7: 'DiffPass7',
  DiffPass8: 'DiffPass8',
  DiffPass9: 'DiffPass9',
  DiffPass10: 'DiffPass10',
  DiffTime1: 'DiffTime1',
  DiffTime2: 'DiffTime2',
  DiffTime3: 'DiffTime3',
  DiffTime4: 'DiffTime4',
  DiffTime5: 'DiffTime5',
  DiffTime6: 'DiffTime6',
  DiffTime7: 'DiffTime7',
  DiffTime8: 'DiffTime8',
  DiffTime9: 'DiffTime9',
  DiffTime10: 'DiffTime10',
  FlagExtraload: 'FlagExtraload'
} as const

export type DatasetCycleScalarFieldEnum = (typeof DatasetCycleScalarFieldEnum)[keyof typeof DatasetCycleScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

