
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FuelTimeLoss_1` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model FuelTimeLoss_1
 * 
 */
export type FuelTimeLoss_1Model = runtime.Types.Result.DefaultSelection<Prisma.$FuelTimeLoss_1Payload>

export type AggregateFuelTimeLoss_1 = {
  _count: FuelTimeLoss_1CountAggregateOutputType | null
  _avg: FuelTimeLoss_1AvgAggregateOutputType | null
  _sum: FuelTimeLoss_1SumAggregateOutputType | null
  _min: FuelTimeLoss_1MinAggregateOutputType | null
  _max: FuelTimeLoss_1MaxAggregateOutputType | null
}

export type FuelTimeLoss_1AvgAggregateOutputType = {
  RecordId: number | null
  DateYear: number | null
  LossFuel: number | null
  LossTime: number | null
}

export type FuelTimeLoss_1SumAggregateOutputType = {
  RecordId: number | null
  DateYear: number | null
  LossFuel: number | null
  LossTime: number | null
}

export type FuelTimeLoss_1MinAggregateOutputType = {
  RecordId: number | null
  DateYear: number | null
  DateMonth: string | null
  OperatorName: string | null
  Crew: string | null
  Reason: string | null
  LossFuel: number | null
  LossTime: number | null
}

export type FuelTimeLoss_1MaxAggregateOutputType = {
  RecordId: number | null
  DateYear: number | null
  DateMonth: string | null
  OperatorName: string | null
  Crew: string | null
  Reason: string | null
  LossFuel: number | null
  LossTime: number | null
}

export type FuelTimeLoss_1CountAggregateOutputType = {
  RecordId: number
  DateYear: number
  DateMonth: number
  OperatorName: number
  Crew: number
  Reason: number
  LossFuel: number
  LossTime: number
  _all: number
}


export type FuelTimeLoss_1AvgAggregateInputType = {
  RecordId?: true
  DateYear?: true
  LossFuel?: true
  LossTime?: true
}

export type FuelTimeLoss_1SumAggregateInputType = {
  RecordId?: true
  DateYear?: true
  LossFuel?: true
  LossTime?: true
}

export type FuelTimeLoss_1MinAggregateInputType = {
  RecordId?: true
  DateYear?: true
  DateMonth?: true
  OperatorName?: true
  Crew?: true
  Reason?: true
  LossFuel?: true
  LossTime?: true
}

export type FuelTimeLoss_1MaxAggregateInputType = {
  RecordId?: true
  DateYear?: true
  DateMonth?: true
  OperatorName?: true
  Crew?: true
  Reason?: true
  LossFuel?: true
  LossTime?: true
}

export type FuelTimeLoss_1CountAggregateInputType = {
  RecordId?: true
  DateYear?: true
  DateMonth?: true
  OperatorName?: true
  Crew?: true
  Reason?: true
  LossFuel?: true
  LossTime?: true
  _all?: true
}

export type FuelTimeLoss_1AggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FuelTimeLoss_1 to aggregate.
   */
  where?: Prisma.FuelTimeLoss_1WhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FuelTimeLoss_1s to fetch.
   */
  orderBy?: Prisma.FuelTimeLoss_1OrderByWithRelationInput | Prisma.FuelTimeLoss_1OrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FuelTimeLoss_1WhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FuelTimeLoss_1s from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FuelTimeLoss_1s.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FuelTimeLoss_1s
  **/
  _count?: true | FuelTimeLoss_1CountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FuelTimeLoss_1AvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FuelTimeLoss_1SumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FuelTimeLoss_1MinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FuelTimeLoss_1MaxAggregateInputType
}

export type GetFuelTimeLoss_1AggregateType<T extends FuelTimeLoss_1AggregateArgs> = {
      [P in keyof T & keyof AggregateFuelTimeLoss_1]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFuelTimeLoss_1[P]>
    : Prisma.GetScalarType<T[P], AggregateFuelTimeLoss_1[P]>
}




export type FuelTimeLoss_1GroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FuelTimeLoss_1WhereInput
  orderBy?: Prisma.FuelTimeLoss_1OrderByWithAggregationInput | Prisma.FuelTimeLoss_1OrderByWithAggregationInput[]
  by: Prisma.FuelTimeLoss_1ScalarFieldEnum[] | Prisma.FuelTimeLoss_1ScalarFieldEnum
  having?: Prisma.FuelTimeLoss_1ScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FuelTimeLoss_1CountAggregateInputType | true
  _avg?: FuelTimeLoss_1AvgAggregateInputType
  _sum?: FuelTimeLoss_1SumAggregateInputType
  _min?: FuelTimeLoss_1MinAggregateInputType
  _max?: FuelTimeLoss_1MaxAggregateInputType
}

export type FuelTimeLoss_1GroupByOutputType = {
  RecordId: number
  DateYear: number | null
  DateMonth: string | null
  OperatorName: string | null
  Crew: string | null
  Reason: string | null
  LossFuel: number | null
  LossTime: number | null
  _count: FuelTimeLoss_1CountAggregateOutputType | null
  _avg: FuelTimeLoss_1AvgAggregateOutputType | null
  _sum: FuelTimeLoss_1SumAggregateOutputType | null
  _min: FuelTimeLoss_1MinAggregateOutputType | null
  _max: FuelTimeLoss_1MaxAggregateOutputType | null
}

type GetFuelTimeLoss_1GroupByPayload<T extends FuelTimeLoss_1GroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FuelTimeLoss_1GroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FuelTimeLoss_1GroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FuelTimeLoss_1GroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FuelTimeLoss_1GroupByOutputType[P]>
      }
    >
  >



export type FuelTimeLoss_1WhereInput = {
  AND?: Prisma.FuelTimeLoss_1WhereInput | Prisma.FuelTimeLoss_1WhereInput[]
  OR?: Prisma.FuelTimeLoss_1WhereInput[]
  NOT?: Prisma.FuelTimeLoss_1WhereInput | Prisma.FuelTimeLoss_1WhereInput[]
  RecordId?: Prisma.IntFilter<"FuelTimeLoss_1"> | number
  DateYear?: Prisma.IntNullableFilter<"FuelTimeLoss_1"> | number | null
  DateMonth?: Prisma.StringNullableFilter<"FuelTimeLoss_1"> | string | null
  OperatorName?: Prisma.StringNullableFilter<"FuelTimeLoss_1"> | string | null
  Crew?: Prisma.StringNullableFilter<"FuelTimeLoss_1"> | string | null
  Reason?: Prisma.StringNullableFilter<"FuelTimeLoss_1"> | string | null
  LossFuel?: Prisma.FloatNullableFilter<"FuelTimeLoss_1"> | number | null
  LossTime?: Prisma.FloatNullableFilter<"FuelTimeLoss_1"> | number | null
}

export type FuelTimeLoss_1OrderByWithRelationInput = {
  RecordId?: Prisma.SortOrder
  DateYear?: Prisma.SortOrderInput | Prisma.SortOrder
  DateMonth?: Prisma.SortOrderInput | Prisma.SortOrder
  OperatorName?: Prisma.SortOrderInput | Prisma.SortOrder
  Crew?: Prisma.SortOrderInput | Prisma.SortOrder
  Reason?: Prisma.SortOrderInput | Prisma.SortOrder
  LossFuel?: Prisma.SortOrderInput | Prisma.SortOrder
  LossTime?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type FuelTimeLoss_1WhereUniqueInput = Prisma.AtLeast<{
  RecordId?: number
  AND?: Prisma.FuelTimeLoss_1WhereInput | Prisma.FuelTimeLoss_1WhereInput[]
  OR?: Prisma.FuelTimeLoss_1WhereInput[]
  NOT?: Prisma.FuelTimeLoss_1WhereInput | Prisma.FuelTimeLoss_1WhereInput[]
  DateYear?: Prisma.IntNullableFilter<"FuelTimeLoss_1"> | number | null
  DateMonth?: Prisma.StringNullableFilter<"FuelTimeLoss_1"> | string | null
  OperatorName?: Prisma.StringNullableFilter<"FuelTimeLoss_1"> | string | null
  Crew?: Prisma.StringNullableFilter<"FuelTimeLoss_1"> | string | null
  Reason?: Prisma.StringNullableFilter<"FuelTimeLoss_1"> | string | null
  LossFuel?: Prisma.FloatNullableFilter<"FuelTimeLoss_1"> | number | null
  LossTime?: Prisma.FloatNullableFilter<"FuelTimeLoss_1"> | number | null
}, "RecordId">

export type FuelTimeLoss_1OrderByWithAggregationInput = {
  RecordId?: Prisma.SortOrder
  DateYear?: Prisma.SortOrderInput | Prisma.SortOrder
  DateMonth?: Prisma.SortOrderInput | Prisma.SortOrder
  OperatorName?: Prisma.SortOrderInput | Prisma.SortOrder
  Crew?: Prisma.SortOrderInput | Prisma.SortOrder
  Reason?: Prisma.SortOrderInput | Prisma.SortOrder
  LossFuel?: Prisma.SortOrderInput | Prisma.SortOrder
  LossTime?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.FuelTimeLoss_1CountOrderByAggregateInput
  _avg?: Prisma.FuelTimeLoss_1AvgOrderByAggregateInput
  _max?: Prisma.FuelTimeLoss_1MaxOrderByAggregateInput
  _min?: Prisma.FuelTimeLoss_1MinOrderByAggregateInput
  _sum?: Prisma.FuelTimeLoss_1SumOrderByAggregateInput
}

export type FuelTimeLoss_1ScalarWhereWithAggregatesInput = {
  AND?: Prisma.FuelTimeLoss_1ScalarWhereWithAggregatesInput | Prisma.FuelTimeLoss_1ScalarWhereWithAggregatesInput[]
  OR?: Prisma.FuelTimeLoss_1ScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FuelTimeLoss_1ScalarWhereWithAggregatesInput | Prisma.FuelTimeLoss_1ScalarWhereWithAggregatesInput[]
  RecordId?: Prisma.IntWithAggregatesFilter<"FuelTimeLoss_1"> | number
  DateYear?: Prisma.IntNullableWithAggregatesFilter<"FuelTimeLoss_1"> | number | null
  DateMonth?: Prisma.StringNullableWithAggregatesFilter<"FuelTimeLoss_1"> | string | null
  OperatorName?: Prisma.StringNullableWithAggregatesFilter<"FuelTimeLoss_1"> | string | null
  Crew?: Prisma.StringNullableWithAggregatesFilter<"FuelTimeLoss_1"> | string | null
  Reason?: Prisma.StringNullableWithAggregatesFilter<"FuelTimeLoss_1"> | string | null
  LossFuel?: Prisma.FloatNullableWithAggregatesFilter<"FuelTimeLoss_1"> | number | null
  LossTime?: Prisma.FloatNullableWithAggregatesFilter<"FuelTimeLoss_1"> | number | null
}

export type FuelTimeLoss_1CreateInput = {
  DateYear?: number | null
  DateMonth?: string | null
  OperatorName?: string | null
  Crew?: string | null
  Reason?: string | null
  LossFuel?: number | null
  LossTime?: number | null
}

export type FuelTimeLoss_1UncheckedCreateInput = {
  RecordId?: number
  DateYear?: number | null
  DateMonth?: string | null
  OperatorName?: string | null
  Crew?: string | null
  Reason?: string | null
  LossFuel?: number | null
  LossTime?: number | null
}

export type FuelTimeLoss_1UpdateInput = {
  DateYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  DateMonth?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  OperatorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Crew?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  LossFuel?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  LossTime?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type FuelTimeLoss_1UncheckedUpdateInput = {
  RecordId?: Prisma.IntFieldUpdateOperationsInput | number
  DateYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  DateMonth?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  OperatorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Crew?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  LossFuel?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  LossTime?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type FuelTimeLoss_1CreateManyInput = {
  DateYear?: number | null
  DateMonth?: string | null
  OperatorName?: string | null
  Crew?: string | null
  Reason?: string | null
  LossFuel?: number | null
  LossTime?: number | null
}

export type FuelTimeLoss_1UpdateManyMutationInput = {
  DateYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  DateMonth?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  OperatorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Crew?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  LossFuel?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  LossTime?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type FuelTimeLoss_1UncheckedUpdateManyInput = {
  RecordId?: Prisma.IntFieldUpdateOperationsInput | number
  DateYear?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  DateMonth?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  OperatorName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Crew?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  Reason?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  LossFuel?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  LossTime?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
}

export type FuelTimeLoss_1CountOrderByAggregateInput = {
  RecordId?: Prisma.SortOrder
  DateYear?: Prisma.SortOrder
  DateMonth?: Prisma.SortOrder
  OperatorName?: Prisma.SortOrder
  Crew?: Prisma.SortOrder
  Reason?: Prisma.SortOrder
  LossFuel?: Prisma.SortOrder
  LossTime?: Prisma.SortOrder
}

export type FuelTimeLoss_1AvgOrderByAggregateInput = {
  RecordId?: Prisma.SortOrder
  DateYear?: Prisma.SortOrder
  LossFuel?: Prisma.SortOrder
  LossTime?: Prisma.SortOrder
}

export type FuelTimeLoss_1MaxOrderByAggregateInput = {
  RecordId?: Prisma.SortOrder
  DateYear?: Prisma.SortOrder
  DateMonth?: Prisma.SortOrder
  OperatorName?: Prisma.SortOrder
  Crew?: Prisma.SortOrder
  Reason?: Prisma.SortOrder
  LossFuel?: Prisma.SortOrder
  LossTime?: Prisma.SortOrder
}

export type FuelTimeLoss_1MinOrderByAggregateInput = {
  RecordId?: Prisma.SortOrder
  DateYear?: Prisma.SortOrder
  DateMonth?: Prisma.SortOrder
  OperatorName?: Prisma.SortOrder
  Crew?: Prisma.SortOrder
  Reason?: Prisma.SortOrder
  LossFuel?: Prisma.SortOrder
  LossTime?: Prisma.SortOrder
}

export type FuelTimeLoss_1SumOrderByAggregateInput = {
  RecordId?: Prisma.SortOrder
  DateYear?: Prisma.SortOrder
  LossFuel?: Prisma.SortOrder
  LossTime?: Prisma.SortOrder
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type FuelTimeLoss_1Select<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  RecordId?: boolean
  DateYear?: boolean
  DateMonth?: boolean
  OperatorName?: boolean
  Crew?: boolean
  Reason?: boolean
  LossFuel?: boolean
  LossTime?: boolean
}, ExtArgs["result"]["fuelTimeLoss_1"]>



export type FuelTimeLoss_1SelectScalar = {
  RecordId?: boolean
  DateYear?: boolean
  DateMonth?: boolean
  OperatorName?: boolean
  Crew?: boolean
  Reason?: boolean
  LossFuel?: boolean
  LossTime?: boolean
}

export type FuelTimeLoss_1Omit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"RecordId" | "DateYear" | "DateMonth" | "OperatorName" | "Crew" | "Reason" | "LossFuel" | "LossTime", ExtArgs["result"]["fuelTimeLoss_1"]>

export type $FuelTimeLoss_1Payload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FuelTimeLoss_1"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    RecordId: number
    DateYear: number | null
    DateMonth: string | null
    OperatorName: string | null
    Crew: string | null
    Reason: string | null
    LossFuel: number | null
    LossTime: number | null
  }, ExtArgs["result"]["fuelTimeLoss_1"]>
  composites: {}
}

export type FuelTimeLoss_1GetPayload<S extends boolean | null | undefined | FuelTimeLoss_1DefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FuelTimeLoss_1Payload, S>

export type FuelTimeLoss_1CountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FuelTimeLoss_1FindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FuelTimeLoss_1CountAggregateInputType | true
  }

export interface FuelTimeLoss_1Delegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FuelTimeLoss_1'], meta: { name: 'FuelTimeLoss_1' } }
  /**
   * Find zero or one FuelTimeLoss_1 that matches the filter.
   * @param {FuelTimeLoss_1FindUniqueArgs} args - Arguments to find a FuelTimeLoss_1
   * @example
   * // Get one FuelTimeLoss_1
   * const fuelTimeLoss_1 = await prisma.fuelTimeLoss_1.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FuelTimeLoss_1FindUniqueArgs>(args: Prisma.SelectSubset<T, FuelTimeLoss_1FindUniqueArgs<ExtArgs>>): Prisma.Prisma__FuelTimeLoss_1Client<runtime.Types.Result.GetResult<Prisma.$FuelTimeLoss_1Payload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FuelTimeLoss_1 that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FuelTimeLoss_1FindUniqueOrThrowArgs} args - Arguments to find a FuelTimeLoss_1
   * @example
   * // Get one FuelTimeLoss_1
   * const fuelTimeLoss_1 = await prisma.fuelTimeLoss_1.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FuelTimeLoss_1FindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FuelTimeLoss_1FindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FuelTimeLoss_1Client<runtime.Types.Result.GetResult<Prisma.$FuelTimeLoss_1Payload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FuelTimeLoss_1 that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FuelTimeLoss_1FindFirstArgs} args - Arguments to find a FuelTimeLoss_1
   * @example
   * // Get one FuelTimeLoss_1
   * const fuelTimeLoss_1 = await prisma.fuelTimeLoss_1.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FuelTimeLoss_1FindFirstArgs>(args?: Prisma.SelectSubset<T, FuelTimeLoss_1FindFirstArgs<ExtArgs>>): Prisma.Prisma__FuelTimeLoss_1Client<runtime.Types.Result.GetResult<Prisma.$FuelTimeLoss_1Payload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FuelTimeLoss_1 that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FuelTimeLoss_1FindFirstOrThrowArgs} args - Arguments to find a FuelTimeLoss_1
   * @example
   * // Get one FuelTimeLoss_1
   * const fuelTimeLoss_1 = await prisma.fuelTimeLoss_1.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FuelTimeLoss_1FindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FuelTimeLoss_1FindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FuelTimeLoss_1Client<runtime.Types.Result.GetResult<Prisma.$FuelTimeLoss_1Payload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FuelTimeLoss_1s that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FuelTimeLoss_1FindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FuelTimeLoss_1s
   * const fuelTimeLoss_1s = await prisma.fuelTimeLoss_1.findMany()
   * 
   * // Get first 10 FuelTimeLoss_1s
   * const fuelTimeLoss_1s = await prisma.fuelTimeLoss_1.findMany({ take: 10 })
   * 
   * // Only select the `RecordId`
   * const fuelTimeLoss_1WithRecordIdOnly = await prisma.fuelTimeLoss_1.findMany({ select: { RecordId: true } })
   * 
   */
  findMany<T extends FuelTimeLoss_1FindManyArgs>(args?: Prisma.SelectSubset<T, FuelTimeLoss_1FindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FuelTimeLoss_1Payload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FuelTimeLoss_1.
   * @param {FuelTimeLoss_1CreateArgs} args - Arguments to create a FuelTimeLoss_1.
   * @example
   * // Create one FuelTimeLoss_1
   * const FuelTimeLoss_1 = await prisma.fuelTimeLoss_1.create({
   *   data: {
   *     // ... data to create a FuelTimeLoss_1
   *   }
   * })
   * 
   */
  create<T extends FuelTimeLoss_1CreateArgs>(args: Prisma.SelectSubset<T, FuelTimeLoss_1CreateArgs<ExtArgs>>): Prisma.Prisma__FuelTimeLoss_1Client<runtime.Types.Result.GetResult<Prisma.$FuelTimeLoss_1Payload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FuelTimeLoss_1s.
   * @param {FuelTimeLoss_1CreateManyArgs} args - Arguments to create many FuelTimeLoss_1s.
   * @example
   * // Create many FuelTimeLoss_1s
   * const fuelTimeLoss_1 = await prisma.fuelTimeLoss_1.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FuelTimeLoss_1CreateManyArgs>(args?: Prisma.SelectSubset<T, FuelTimeLoss_1CreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a FuelTimeLoss_1.
   * @param {FuelTimeLoss_1DeleteArgs} args - Arguments to delete one FuelTimeLoss_1.
   * @example
   * // Delete one FuelTimeLoss_1
   * const FuelTimeLoss_1 = await prisma.fuelTimeLoss_1.delete({
   *   where: {
   *     // ... filter to delete one FuelTimeLoss_1
   *   }
   * })
   * 
   */
  delete<T extends FuelTimeLoss_1DeleteArgs>(args: Prisma.SelectSubset<T, FuelTimeLoss_1DeleteArgs<ExtArgs>>): Prisma.Prisma__FuelTimeLoss_1Client<runtime.Types.Result.GetResult<Prisma.$FuelTimeLoss_1Payload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FuelTimeLoss_1.
   * @param {FuelTimeLoss_1UpdateArgs} args - Arguments to update one FuelTimeLoss_1.
   * @example
   * // Update one FuelTimeLoss_1
   * const fuelTimeLoss_1 = await prisma.fuelTimeLoss_1.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FuelTimeLoss_1UpdateArgs>(args: Prisma.SelectSubset<T, FuelTimeLoss_1UpdateArgs<ExtArgs>>): Prisma.Prisma__FuelTimeLoss_1Client<runtime.Types.Result.GetResult<Prisma.$FuelTimeLoss_1Payload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FuelTimeLoss_1s.
   * @param {FuelTimeLoss_1DeleteManyArgs} args - Arguments to filter FuelTimeLoss_1s to delete.
   * @example
   * // Delete a few FuelTimeLoss_1s
   * const { count } = await prisma.fuelTimeLoss_1.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FuelTimeLoss_1DeleteManyArgs>(args?: Prisma.SelectSubset<T, FuelTimeLoss_1DeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FuelTimeLoss_1s.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FuelTimeLoss_1UpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FuelTimeLoss_1s
   * const fuelTimeLoss_1 = await prisma.fuelTimeLoss_1.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FuelTimeLoss_1UpdateManyArgs>(args: Prisma.SelectSubset<T, FuelTimeLoss_1UpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one FuelTimeLoss_1.
   * @param {FuelTimeLoss_1UpsertArgs} args - Arguments to update or create a FuelTimeLoss_1.
   * @example
   * // Update or create a FuelTimeLoss_1
   * const fuelTimeLoss_1 = await prisma.fuelTimeLoss_1.upsert({
   *   create: {
   *     // ... data to create a FuelTimeLoss_1
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FuelTimeLoss_1 we want to update
   *   }
   * })
   */
  upsert<T extends FuelTimeLoss_1UpsertArgs>(args: Prisma.SelectSubset<T, FuelTimeLoss_1UpsertArgs<ExtArgs>>): Prisma.Prisma__FuelTimeLoss_1Client<runtime.Types.Result.GetResult<Prisma.$FuelTimeLoss_1Payload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FuelTimeLoss_1s.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FuelTimeLoss_1CountArgs} args - Arguments to filter FuelTimeLoss_1s to count.
   * @example
   * // Count the number of FuelTimeLoss_1s
   * const count = await prisma.fuelTimeLoss_1.count({
   *   where: {
   *     // ... the filter for the FuelTimeLoss_1s we want to count
   *   }
   * })
  **/
  count<T extends FuelTimeLoss_1CountArgs>(
    args?: Prisma.Subset<T, FuelTimeLoss_1CountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FuelTimeLoss_1CountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FuelTimeLoss_1.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FuelTimeLoss_1AggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FuelTimeLoss_1AggregateArgs>(args: Prisma.Subset<T, FuelTimeLoss_1AggregateArgs>): Prisma.PrismaPromise<GetFuelTimeLoss_1AggregateType<T>>

  /**
   * Group by FuelTimeLoss_1.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FuelTimeLoss_1GroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FuelTimeLoss_1GroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FuelTimeLoss_1GroupByArgs['orderBy'] }
      : { orderBy?: FuelTimeLoss_1GroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FuelTimeLoss_1GroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFuelTimeLoss_1GroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FuelTimeLoss_1 model
 */
readonly fields: FuelTimeLoss_1FieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FuelTimeLoss_1.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FuelTimeLoss_1Client<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FuelTimeLoss_1 model
 */
export interface FuelTimeLoss_1FieldRefs {
  readonly RecordId: Prisma.FieldRef<"FuelTimeLoss_1", 'Int'>
  readonly DateYear: Prisma.FieldRef<"FuelTimeLoss_1", 'Int'>
  readonly DateMonth: Prisma.FieldRef<"FuelTimeLoss_1", 'String'>
  readonly OperatorName: Prisma.FieldRef<"FuelTimeLoss_1", 'String'>
  readonly Crew: Prisma.FieldRef<"FuelTimeLoss_1", 'String'>
  readonly Reason: Prisma.FieldRef<"FuelTimeLoss_1", 'String'>
  readonly LossFuel: Prisma.FieldRef<"FuelTimeLoss_1", 'Float'>
  readonly LossTime: Prisma.FieldRef<"FuelTimeLoss_1", 'Float'>
}
    

// Custom InputTypes
/**
 * FuelTimeLoss_1 findUnique
 */
export type FuelTimeLoss_1FindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FuelTimeLoss_1
   */
  select?: Prisma.FuelTimeLoss_1Select<ExtArgs> | null
  /**
   * Omit specific fields from the FuelTimeLoss_1
   */
  omit?: Prisma.FuelTimeLoss_1Omit<ExtArgs> | null
  /**
   * Filter, which FuelTimeLoss_1 to fetch.
   */
  where: Prisma.FuelTimeLoss_1WhereUniqueInput
}

/**
 * FuelTimeLoss_1 findUniqueOrThrow
 */
export type FuelTimeLoss_1FindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FuelTimeLoss_1
   */
  select?: Prisma.FuelTimeLoss_1Select<ExtArgs> | null
  /**
   * Omit specific fields from the FuelTimeLoss_1
   */
  omit?: Prisma.FuelTimeLoss_1Omit<ExtArgs> | null
  /**
   * Filter, which FuelTimeLoss_1 to fetch.
   */
  where: Prisma.FuelTimeLoss_1WhereUniqueInput
}

/**
 * FuelTimeLoss_1 findFirst
 */
export type FuelTimeLoss_1FindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FuelTimeLoss_1
   */
  select?: Prisma.FuelTimeLoss_1Select<ExtArgs> | null
  /**
   * Omit specific fields from the FuelTimeLoss_1
   */
  omit?: Prisma.FuelTimeLoss_1Omit<ExtArgs> | null
  /**
   * Filter, which FuelTimeLoss_1 to fetch.
   */
  where?: Prisma.FuelTimeLoss_1WhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FuelTimeLoss_1s to fetch.
   */
  orderBy?: Prisma.FuelTimeLoss_1OrderByWithRelationInput | Prisma.FuelTimeLoss_1OrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FuelTimeLoss_1s.
   */
  cursor?: Prisma.FuelTimeLoss_1WhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FuelTimeLoss_1s from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FuelTimeLoss_1s.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FuelTimeLoss_1s.
   */
  distinct?: Prisma.FuelTimeLoss_1ScalarFieldEnum | Prisma.FuelTimeLoss_1ScalarFieldEnum[]
}

/**
 * FuelTimeLoss_1 findFirstOrThrow
 */
export type FuelTimeLoss_1FindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FuelTimeLoss_1
   */
  select?: Prisma.FuelTimeLoss_1Select<ExtArgs> | null
  /**
   * Omit specific fields from the FuelTimeLoss_1
   */
  omit?: Prisma.FuelTimeLoss_1Omit<ExtArgs> | null
  /**
   * Filter, which FuelTimeLoss_1 to fetch.
   */
  where?: Prisma.FuelTimeLoss_1WhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FuelTimeLoss_1s to fetch.
   */
  orderBy?: Prisma.FuelTimeLoss_1OrderByWithRelationInput | Prisma.FuelTimeLoss_1OrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FuelTimeLoss_1s.
   */
  cursor?: Prisma.FuelTimeLoss_1WhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FuelTimeLoss_1s from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FuelTimeLoss_1s.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FuelTimeLoss_1s.
   */
  distinct?: Prisma.FuelTimeLoss_1ScalarFieldEnum | Prisma.FuelTimeLoss_1ScalarFieldEnum[]
}

/**
 * FuelTimeLoss_1 findMany
 */
export type FuelTimeLoss_1FindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FuelTimeLoss_1
   */
  select?: Prisma.FuelTimeLoss_1Select<ExtArgs> | null
  /**
   * Omit specific fields from the FuelTimeLoss_1
   */
  omit?: Prisma.FuelTimeLoss_1Omit<ExtArgs> | null
  /**
   * Filter, which FuelTimeLoss_1s to fetch.
   */
  where?: Prisma.FuelTimeLoss_1WhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FuelTimeLoss_1s to fetch.
   */
  orderBy?: Prisma.FuelTimeLoss_1OrderByWithRelationInput | Prisma.FuelTimeLoss_1OrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FuelTimeLoss_1s.
   */
  cursor?: Prisma.FuelTimeLoss_1WhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FuelTimeLoss_1s from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FuelTimeLoss_1s.
   */
  skip?: number
  distinct?: Prisma.FuelTimeLoss_1ScalarFieldEnum | Prisma.FuelTimeLoss_1ScalarFieldEnum[]
}

/**
 * FuelTimeLoss_1 create
 */
export type FuelTimeLoss_1CreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FuelTimeLoss_1
   */
  select?: Prisma.FuelTimeLoss_1Select<ExtArgs> | null
  /**
   * Omit specific fields from the FuelTimeLoss_1
   */
  omit?: Prisma.FuelTimeLoss_1Omit<ExtArgs> | null
  /**
   * The data needed to create a FuelTimeLoss_1.
   */
  data?: Prisma.XOR<Prisma.FuelTimeLoss_1CreateInput, Prisma.FuelTimeLoss_1UncheckedCreateInput>
}

/**
 * FuelTimeLoss_1 createMany
 */
export type FuelTimeLoss_1CreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FuelTimeLoss_1s.
   */
  data: Prisma.FuelTimeLoss_1CreateManyInput | Prisma.FuelTimeLoss_1CreateManyInput[]
}

/**
 * FuelTimeLoss_1 update
 */
export type FuelTimeLoss_1UpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FuelTimeLoss_1
   */
  select?: Prisma.FuelTimeLoss_1Select<ExtArgs> | null
  /**
   * Omit specific fields from the FuelTimeLoss_1
   */
  omit?: Prisma.FuelTimeLoss_1Omit<ExtArgs> | null
  /**
   * The data needed to update a FuelTimeLoss_1.
   */
  data: Prisma.XOR<Prisma.FuelTimeLoss_1UpdateInput, Prisma.FuelTimeLoss_1UncheckedUpdateInput>
  /**
   * Choose, which FuelTimeLoss_1 to update.
   */
  where: Prisma.FuelTimeLoss_1WhereUniqueInput
}

/**
 * FuelTimeLoss_1 updateMany
 */
export type FuelTimeLoss_1UpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FuelTimeLoss_1s.
   */
  data: Prisma.XOR<Prisma.FuelTimeLoss_1UpdateManyMutationInput, Prisma.FuelTimeLoss_1UncheckedUpdateManyInput>
  /**
   * Filter which FuelTimeLoss_1s to update
   */
  where?: Prisma.FuelTimeLoss_1WhereInput
  /**
   * Limit how many FuelTimeLoss_1s to update.
   */
  limit?: number
}

/**
 * FuelTimeLoss_1 upsert
 */
export type FuelTimeLoss_1UpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FuelTimeLoss_1
   */
  select?: Prisma.FuelTimeLoss_1Select<ExtArgs> | null
  /**
   * Omit specific fields from the FuelTimeLoss_1
   */
  omit?: Prisma.FuelTimeLoss_1Omit<ExtArgs> | null
  /**
   * The filter to search for the FuelTimeLoss_1 to update in case it exists.
   */
  where: Prisma.FuelTimeLoss_1WhereUniqueInput
  /**
   * In case the FuelTimeLoss_1 found by the `where` argument doesn't exist, create a new FuelTimeLoss_1 with this data.
   */
  create: Prisma.XOR<Prisma.FuelTimeLoss_1CreateInput, Prisma.FuelTimeLoss_1UncheckedCreateInput>
  /**
   * In case the FuelTimeLoss_1 was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FuelTimeLoss_1UpdateInput, Prisma.FuelTimeLoss_1UncheckedUpdateInput>
}

/**
 * FuelTimeLoss_1 delete
 */
export type FuelTimeLoss_1DeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FuelTimeLoss_1
   */
  select?: Prisma.FuelTimeLoss_1Select<ExtArgs> | null
  /**
   * Omit specific fields from the FuelTimeLoss_1
   */
  omit?: Prisma.FuelTimeLoss_1Omit<ExtArgs> | null
  /**
   * Filter which FuelTimeLoss_1 to delete.
   */
  where: Prisma.FuelTimeLoss_1WhereUniqueInput
}

/**
 * FuelTimeLoss_1 deleteMany
 */
export type FuelTimeLoss_1DeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FuelTimeLoss_1s to delete
   */
  where?: Prisma.FuelTimeLoss_1WhereInput
  /**
   * Limit how many FuelTimeLoss_1s to delete.
   */
  limit?: number
}

/**
 * FuelTimeLoss_1 without action
 */
export type FuelTimeLoss_1DefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FuelTimeLoss_1
   */
  select?: Prisma.FuelTimeLoss_1Select<ExtArgs> | null
  /**
   * Omit specific fields from the FuelTimeLoss_1
   */
  omit?: Prisma.FuelTimeLoss_1Omit<ExtArgs> | null
}
